### ISSUE TITLE
Config.json to change or remove Right Ctrl hotkey

### ISSUE THREAD

**Issue by rgon842** [Enaium-StardewValleyMods/EnaiumToolKit#18]
Hello,

It looks like this toolkit uses the Right Ctrl key to bring up a testing menu within Stardew Valley, and because it is capturing that input, we are unable to assign Right Ctrl to another command or as a modifier for a key combination.

Would it be possible to add a config.json file to this toolkit so that the key binding for this menu can be changed, or disabled entirely? Thank you.

**Comment by Enaium** [comment]
You can't change this hotkey at the moment, but you can change another mod's hotkey with [this mod](https://github.com/Enaium/sdv-mod-KeyBindUI).

**Comment by Enaium** [comment]
you can change this hotkey now, and I recommend using [this mod](https://www.curseforge.com/stardewvalley/mods/keybindui)

**Comment by Tearlow** [comment]
So let me get this straight, to change the keybind I need another mod to be able to change the keybind for this mod? What if I don't want to change it but simply remove it? I think it's safe to say that 99.9999% have no use for a testing menu and should be defaulted to disabled altogether.

**Comment by Enaium** [comment]
> So let me get this straight, to change the keybind I need another mod to be able to change the keybind for this mod? What if I don't want to change it but simply remove it? I think it's safe to say that 99.9999% have no use for a testing menu and should be defaulted to disabled altogether.

I will remove the keybind soon.

**Comment by Tearlow** [comment]
Just a note but... Looking at the new manifest at the version string; https://github.com/Enaium/sdv-mod-EnaiumToolKit/blob/d512dcf662672826649f549d0dc98857dab89f8c/EnaiumToolKit/manifest.json#L4

You released this update as 1.8.0 on curseforge which is a bit confusing seeing as it was released once before. I doubt it does anything but I figured I'd at least mention it.
